apiVersion: v1
kind: Service
metadata:
  name: {{ include "tankroyaleserver.fullname" . }}
  labels:
    {{- include "tankroyaleserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.port }}-tcp
  selector:
    {{- include "tankroyaleserver.selectorLabels" . | nindent 4 }}
