apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for tank-royale.quay.io/v1alpha1, Kind: TankRoyaleServer
##
- apiGroups:
  - tank-royale.quay.io
  resources:
  - tankroyaleservers
  - tankroyaleservers/status
  - tankroyaleservers/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
  - "configmaps"
- verbs:
  - '*'
  apiGroups:
    - route.openshift.io
  resources:
    - routes
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

##
## Rules for tank-royale.quay.io/v1alpha1, Kind: TankRoyaleBot
##
- apiGroups:
  - tank-royale.quay.io
  resources:
  - tankroyalebots
  - tankroyalebots/status
  - tankroyalebots/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

#+kubebuilder:scaffold:rules
