# permissions for end users to edit tankroyalebots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tankroyalebot-editor-role
rules:
- apiGroups:
  - tank-royale.quay.io
  resources:
  - tankroyalebots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tank-royale.quay.io
  resources:
  - tankroyalebots/status
  verbs:
  - get
