# permissions for end users to view tankroyalebots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tankroyalebot-viewer-role
rules:
- apiGroups:
  - tank-royale.quay.io
  resources:
  - tankroyalebots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tank-royale.quay.io
  resources:
  - tankroyalebots/status
  verbs:
  - get
