# permissions for end users to view tankroyaleservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tankroyaleserver-viewer-role
rules:
- apiGroups:
  - tank-royale.quay.io
  resources:
  - tankroyaleservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tank-royale.quay.io
  resources:
  - tankroyaleservers/status
  verbs:
  - get
